import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Portfolio from './Portfolio'
import Card from '../components/Card'
import About from '../components/About'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Portfolio /> */}
      {/* <Card /> */}
      <About />

      
    
    </div>
  )
}

export default Home
